/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Milog;

import com.sun.tools.javac.Main;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    private static final Logger logger = LogManager.getLogger(Main.class);
    
    public static void main(String[] args) {
      
  
        
        logger.info("Ingreso al proyecto");
        
    }
}
