/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Milog;

import org.apache.logging.log4j.Level;
import com.sun.tools.javac.Main;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
 private static final Logger miLogLevel = LogManager.getLogger(Main.class);
//   final Level VERBOSE = Level.forName("VERBOSE", 550);

 
    public static void main(String[] args) {
      
//        App app = new App();
  
        
//          Ingreso de Verbose creado desde el main 
//        miLogLevel.log(app.VERBOSE, "Ha ingresado al VERBOSE (new level)");
//          Metodo para ingresar al Level creado desde log4j2.xml
          miLogLevel.log(Level.getLevel("VERBOSE"), "Ha ingresado al VERBOSE (new level desde config.)");

    }
}
